apiVersion: v1
kind: Service
metadata:
  labels:
    app: events-website-svc
  name: events-website-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: events-website
  type: LoadBalancer
