apiVersion: v2
name: events
description: AWS ER Capstone demo app

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:
  - name: mariadb
    version: "20.5.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
